-- MySQL Script generated by MySQL Workbench
-- Qua 01 Jun 2016 20:19:01 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

CREATE DATABASE thegeekstuff;
USE `thegeekstuff` ;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema thegeekstuff
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `thegeekstuff` DEFAULT CHARACTER SET utf8 ;

-- -----------------------------------------------------
-- Table `thegeekstuff`.`employee`
-- -----------------------------------------------------
CREATE TABLE `employee` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name varchar(20),
  dept varchar(10),
  salary int(10)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;  

-- -----------------------------------------------------
-- Insert `employee`
-- -----------------------------------------------------
INSERT INTO employee VALUES (100,'Thomas','Sales',5000);
INSERT INTO employee VALUES (200,'Jason','Technology',5500);
INSERT INTO employee VALUES (300,'Mayla','Technology',7000);
INSERT INTO employee VALUES (400,'Nisha','Marketing',9500);
INSERT INTO employee VALUES (500,'Randy','Technology',6000);
INSERT INTO employee VALUES (7369,'Smith','Accounting',3000);
INSERT INTO employee VALUES (7499,'Allen','Accounting',3000);
INSERT INTO employee VALUES (7521,'Ward','Finance',2500);
INSERT INTO employee VALUES (7566,'Jones','Finance',2500);
INSERT INTO employee VALUES (7654,'Martin','Finance',2500);
INSERT INTO employee VALUES (7698,'Blake','Manager', 15000);
INSERT INTO employee VALUES (7782,'Clark','Manager', 15000);
INSERT INTO employee VALUES (7788,'Scott','Manager', 15000);
INSERT INTO employee VALUES (7839,'King','Marketing',10000);
INSERT INTO employee VALUES (7844,'Turner','Marketing',10000);
INSERT INTO employee VALUES (7876,'Adams','Marketing',10000);
INSERT INTO employee VALUES (7900,'James','Technology',6000);
INSERT INTO employee VALUES (7902,'Ford','Technology',4500);
INSERT INTO employee VALUES (7934,'Miller','Process',2000);